import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class RemuxAuthException implements Exception { RemuxAuthException(this.message); final String message; @override String toString() => 'RemuxAuthException: $message'; }
class RemuxConnectionException implements Exception { RemuxConnectionException(this.message, {this.statusCode}); final String message; final int? statusCode; @override String toString() => 'RemuxConnectionException: $message'; }
class RemuxEngine {
 RemuxEngine({this.onError}) { player=Player(configuration: const PlayerConfiguration()); controller=VideoController(player); _subscriptions=[player.stream.error.listen(_handleError),player.stream.playing.listen(_handlePlayingChanged),player.stream.buffering.listen(_handleBufferingChanged)]; }
 late final Player player; late final VideoController controller; final void Function(String error)? onError; final ValueNotifier<String?> error=ValueNotifier(null); final ValueNotifier<bool> playing=ValueNotifier(false); final ValueNotifier<bool> buffering=ValueNotifier(false); late final List<StreamSubscription<Object?>> _subscriptions; Uri? _uri; Map<String,String> _headers={}; int _retryCount=0; bool _retryScheduled=false; bool _disposed=false; static const int _maxRetries=3;
 List<AudioTrack> get audioTracks => player.state.audioTracks; List<SubtitleTrack> get subtitleTracks => player.state.subtitleTracks; AudioTrack? get selectedAudioTrack => player.state.track.audio; SubtitleTrack? get selectedSubtitleTrack => player.state.track.subtitle;
 Future<void> selectAudioTrack(AudioTrack track) => player.setAudioTrack(track); Future<void> selectSubtitleTrack(SubtitleTrack track) => player.setSubtitleTrack(track); Future<void> disableSubtitles() => player.setSubtitleTrack(SubtitleTrack.no());
 @visibleForTesting int get retryCount=>_retryCount; @visibleForTesting int get maxRetries=>_maxRetries; @visibleForTesting Duration retryDelayForAttempt(int attempt)=>Duration(seconds:1<<(attempt-1));
 static const Map<String,String> mpvProperties={'hwdec':'auto-safe','vo':'gpu-next','demuxer-max-bytes':'512MiB','demuxer-max-back-bytes':'256MiB','cache':'yes','network-timeout':'15','socket-buffer-size':'4MiB','tone-mapping':'bt.2446a','target-colorspace-hint':'yes','audio-spdif':'ac3,eac3,dts,dts-hd,truehd','audio-passthrough':'yes','audio-fallback-to-null':'no','sub-auto':'fuzzy','sub-ass':'yes','sub-forced':'yes'};
 static Map<String,String> get effectiveMpvProperties=>Map.unmodifiable({...mpvProperties,'audio-device':'auto'});
 Future<void> open(Uri uri,{String? title,Map<String,String>? headers,String? authToken}) async { _uri=uri;_retryCount=0;_retryScheduled=false;error.value=null;_headers={...?headers};if(authToken!=null&&authToken.isNotEmpty)_headers['Authorization']='Bearer $authToken';await _openAtPosition(); }
 Future<void> _openAtPosition() async { final uri=_uri;if(_disposed||uri==null)return;final position=player.state.position;final media=Media(uri.toString(),httpHeaders:_headers);for(final e in effectiveMpvProperties.entries){media.extras?[e.key]=e.value;}await player.open(media,play:true);if(position>Duration.zero)await player.seek(position); }
 void _handleError(String message){if(_disposed)return;error.value=message;onError?.call(message);if(_retryScheduled||_retryCount>=_maxRetries||_uri==null)return;_retryScheduled=true;_retryCount++;unawaited(_retry());} Future<void> retry()async{if(_disposed||_uri==null)return;_retryScheduled=false;try{await _openAtPosition();error.value=null;}on Object catch(e){_handleError(e.toString());}} Future<void> _retry()async{await Future<void>.delayed(retryDelayForAttempt(_retryCount));await retry();} void _handlePlayingChanged(bool v){if(!_disposed)playing.value=v;} void _handleBufferingChanged(bool v){if(!_disposed)buffering.value=v;} Future<void> seek(Duration p)=>player.seek(p); Future<void> dispose()async{if(_disposed)return;_disposed=true;for(final s in _subscriptions){await s.cancel();}error.dispose();playing.dispose();buffering.dispose();await player.dispose();}
}
@Deprecated('Use RemuxEngine instead.') typedef RodPlayerEngine=RemuxEngine;
