import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:rodplayer/core/api/remux_client.dart';
import 'package:rodplayer/core/models/media_intelligence.dart';
import 'package:rodplayer/core/theme/remux_theme.dart';
import 'package:rodplayer/ui/widgets/compatibility_panel.dart';
import 'package:rodplayer/ui/widgets/focusable_media_card.dart';
import 'package:rodplayer/ui/widgets/media_badge.dart';
import 'package:rodplayer/ui/widgets/media_bar.dart';
import 'package:rodplayer/ui/widgets/quick_actions_sheet.dart';
import 'package:rodplayer/ui/widgets/remux_logo.dart';
import 'package:rodplayer/ui/widgets/smart_shelf.dart';

class BrowseScreen extends StatefulWidget { const BrowseScreen({required this.client, this.onLogout = _defaultLogout, super.key}); final RemuxClient client; final Future<void> Function() onLogout; static Future<void> _defaultLogout() async {} @override State<BrowseScreen> createState() => _BrowseScreenState(); }
class _BrowseScreenState extends State<BrowseScreen> {
  final _scrollController = ScrollController();
  static const _posters = ['https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg','https://image.tmdb.org/t/p/w500/1XDDXPXGI7p8DhvjniLyrzsyVSj.jpg'];
  @override void initState() { super.initState(); widget.client.getItems().then<void>((_) {}, onError: (Object error, StackTrace stackTrace) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Unable to load library: $error'))); }); }
  @override void dispose() { _scrollController.dispose(); super.dispose(); }
  Widget _card(String title, int i, {double aspectRatio = 2 / 3}) { final card = FocusableMediaCard(title: title, subtitle: aspectRatio > 1 ? '${(i + 1) * 12}% watched' : 'Movie', imageUrl: _posters[i % _posters.length], aspectRatio: aspectRatio, mediaInfo: const MediaIntelligence(width: 3840, height: 2160, video: StreamIntelligence(type: 'Video', codec: 'hevc', videoRange: 'HDR10+'), audio: StreamIntelligence(type: 'Audio', codec: 'truehd', channels: 8, channelLayout: '7.1')), onTap: () {}); return GestureDetector(onLongPress: () => showQuickActionsSheet(context, title: title), child: card); }
  Widget _shelf(String title, List<String> items, {double aspectRatio = 2 / 3}) => SmartShelf(title: title, itemCount: items.length, aspectRatio: aspectRatio, itemCountBadge: true, autofocusFirstItem: true, itemBuilder: (context, index) => _card(items[index], index, aspectRatio: aspectRatio));
  @override Widget build(BuildContext context) { final t = Theme.of(context).extension<RemuxTheme>() ?? const RemuxTheme(); return PopScope(canPop: true, child: Scaffold(backgroundColor: t.obsidian, body: FocusTraversalGroup(policy: OrderedTraversalPolicy(), child: CustomScrollView(controller: _scrollController, slivers: [SliverAppBar(pinned: true, expandedHeight: 128, backgroundColor: Colors.transparent, surfaceTintColor: Colors.transparent, flexibleSpace: ClipRect(child: BackdropFilter(filter: ImageFilter.blur(sigmaX: t.glassBlur, sigmaY: t.glassBlur), child: DecoratedBox(decoration: BoxDecoration(color: t.surface3.withValues(alpha: 0.86), border: Border(bottom: BorderSide(color: t.borderColor()))), child: FlexibleSpaceBar(titlePadding: const EdgeInsetsDirectional.only(start: 24, bottom: 16), title: const Text('Browse'), background: Padding(padding: const EdgeInsets.fromLTRB(24, 28, 24, 52), child: Row(children: [const RemuxLogo(size: 34, glow: true), const SizedBox(width: 10), Text('Remux', style: TextStyle(color: Color(0xFFEBCF52), fontWeight: FontWeight.w700)), const Spacer(), TextButton.icon(onPressed: () {}, icon: const Icon(Icons.shuffle), label: const Text('Surprise Me'))])))))), actions: [IconButton(onPressed: widget.onLogout, icon: const Icon(Icons.logout))]), SliverToBoxAdapter(child: LayoutBuilder(builder: (context, constraints) { final height = MediaQuery.sizeOf(context).height; final heroHeight = (height * 0.53).clamp(300.0, 500.0); return Padding(padding: const EdgeInsets.all(24), child: Container(height: heroHeight, decoration: BoxDecoration(borderRadius: BorderRadius.circular(t.radiusXLarge), gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [t.green, t.surface2]), border: Border.all(color: t.borderColor(0.15)), boxShadow: t.glassShadow), child: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [const Text('Featured collection', style: TextStyle(fontSize: 28, fontWeight: FontWeight.w700)), const SizedBox(height: 10), const MediaBadges(labels: ['4K','HDR10+','Atmos','HEVC']), const SizedBox(height: 14), Row(children: [FilledButton.icon(onPressed: () {}, icon: const Icon(Icons.play_arrow), label: const Text('Quick Play')), const SizedBox(width: 12), OutlinedButton(onPressed: () => showModalBottomSheet<void>(context: context, builder: (_) => const Padding(padding: EdgeInsets.all(16), child: CompatibilityPanel())), child: const Text('Inspect'))])]))); })), SliverToBoxAdapter(child: _shelf('Continue Watching', ['The Last Voyage','Shoreline','Night Shift'], aspectRatio: 16 / 9)), SliverToBoxAdapter(child: _shelf('Top Picks', ['Afterlight','Signal Fire','Open Water','The Crossing'])), SliverToBoxAdapter(child: _shelf('Movies', ['The Archive','Horizon','The Long Road','Northbound'])), const SliverPadding(padding: EdgeInsets.only(bottom: 32))])))); }
}
