import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:uuid/uuid.dart';
import 'package:rodplayer/core/playback/playback_decision.dart';
import 'package:rodplayer/core/playback/platform_capabilities.dart';

class PlaybackStreamInfo { const PlaybackStreamInfo({required this.itemId, required this.mediaSourceId, required this.playMethod}); final String itemId; final String mediaSourceId; final String playMethod; }
class RemuxAuthException implements Exception { RemuxAuthException(this.message); final String message; @override String toString() => 'RemuxAuthException: $message'; }
class RemuxConnectionException implements Exception { RemuxConnectionException(this.message, {this.statusCode}); final String message; final int? statusCode; @override String toString() => 'RemuxConnectionException: $message'; }

class RemuxClient {
  RemuxClient({required String baseUrl, http.Client? client}) : baseUrl = baseUrl.replaceFirst(RegExp(r'/$'), ''), _client = client ?? http.Client(), deviceId = const Uuid().v4();
  final String baseUrl; final http.Client _client; final String deviceId; String? accessToken; String? userId; String? sessionId;
  Map<String, String> get _headers { final token = _cleanToken(accessToken); final authorization = StringBuffer('MediaBrowser Client="rodplayer", Device="FireTV", DeviceId="$deviceId", Version="1.0.0"'); if (token != null) authorization.write(', Token="$token"'); return {'Accept': 'application/json', 'Content-Type': 'application/json', 'Authorization': authorization.toString()}; }
  static String? _cleanToken(String? token) { final value = token?.trim(); if (value == null || value.isEmpty) return null; return value.replaceFirst(RegExp(r'^Bearer\s+', caseSensitive: false), '').trim(); }
  Future<Map<String, dynamic>> healthCheck() async { try { final response = await _client.get(Uri.parse('$baseUrl/System/Info/Public')); _check(response); return jsonDecode(response.body) as Map<String, dynamic>; } catch (error) { if (error is RemuxConnectionException) rethrow; throw RemuxConnectionException('Unable to reach Remux server: $error'); } }
  Future<void> authenticate({required String username, required String password}) async { final response = await _client.post(Uri.parse('$baseUrl/Users/AuthenticateByName'), headers: _headers, body: jsonEncode({'Username': username, 'Pw': password})); if (response.statusCode == 401 || response.statusCode == 403) throw RemuxAuthException('Jellyfin rejected the supplied credentials (${response.statusCode})'); _check(response); final data = jsonDecode(response.body) as Map<String, dynamic>; accessToken = data['AccessToken'] as String?; userId = (data['User'] as Map<String, dynamic>?)?['Id'] as String?; if (accessToken == null || userId == null) throw RemuxAuthException('Authentication response did not include AccessToken and User.Id'); }
  String _userQuery() { final id = userId; if (id == null || id.isEmpty) throw RemuxAuthException('Authenticate before requesting user items'); return 'UserId=${Uri.encodeQueryComponent(id)}'; }
  List<dynamic> _items(http.Response response, {String key = 'Items'}) { _check(response); final data = jsonDecode(response.body) as Map<String, dynamic>; return (data[key] as List<dynamic>?) ?? []; }
  Future<List<dynamic>> getItems() async => _items(await _client.get(Uri.parse('$baseUrl/Items?${_userQuery()}'), headers: _headers));
  Future<List<dynamic>> getLatestMovies({int limit = 20}) async => _items(await _client.get(Uri.parse('$baseUrl/Items?${_userQuery()}&IncludeItemTypes=Movie&Recursive=true&SortBy=DateCreated&SortOrder=Descending&Limit=$limit&Fields=PrimaryImageAspectRatio,UserData'), headers: _headers));
  Future<List<dynamic>> getLatestTvShows({int limit = 20}) async => _items(await _client.get(Uri.parse('$baseUrl/Items?${_userQuery()}&IncludeItemTypes=Series&Recursive=true&SortBy=DateCreated&SortOrder=Descending&Limit=$limit&Fields=PrimaryImageAspectRatio,UserData'), headers: _headers));
  Future<List<dynamic>> getNextUp({int limit = 12}) async => _items(await _client.get(Uri.parse('$baseUrl/Shows/NextUp?${_userQuery()}&Limit=$limit&Fields=PrimaryImageAspectRatio,UserData,SeriesName,SeasonNumber,IndexNumber,RunTimeTicks'), headers: _headers));
  Future<List<dynamic>> getResumeItems({int limit = 12}) async => _items(await _client.get(Uri.parse('$baseUrl/Items?${_userQuery()}&Filters=IsResumable&Recursive=true&SortBy=DatePlayed&SortOrder=Descending&Limit=$limit&Fields=PrimaryImageAspectRatio,BackdropImageTags,UserData,SeriesName,SeasonNumber,IndexNumber,RunTimeTicks'), headers: _headers));
  Future<List<dynamic>> getUserViews() async => _items(await _client.get(Uri.parse('$baseUrl/Users/$userId/Views'), headers: _headers));
  Future<List<dynamic>> search({required String query, int limit = 20}) async => _items(await _client.get(Uri.parse('$baseUrl/Search/Hints?${_userQuery()}&SearchTerm=${Uri.encodeQueryComponent(query)}&Limit=$limit&IncludeItemTypes=Movie,Series,Episode'), headers: _headers), key: 'SearchHints');
  Future<void> toggleFavorite({required String itemId, required bool isFavorite}) async { final uri = Uri.parse('$baseUrl/Users/$userId/FavoriteItems/$itemId'); final response = isFavorite ? await _client.post(uri, headers: _headers) : await _client.delete(uri); _check(response); }
  Future<Uri> getStreamUri(String itemId) async { final response = await _client.post(Uri.parse('$baseUrl/Items/$itemId/PlaybackInfo?${_userQuery()}'), headers: _headers, body: jsonEncode({'DeviceProfile': DeviceCapabilities.forProfile(DeviceCapabilities.currentProfile()).toDeviceProfile(), 'StartTimeTicks': 0})); _check(response); final data = jsonDecode(response.body) as Map<String, dynamic>; final sources = data['MediaSources'] as List<dynamic>? ?? []; final engine = PlaybackDecisionEngine(DeviceCapabilities.forProfile(DeviceCapabilities.currentProfile())); for (final value in sources) { if (value is! Map<String, dynamic>) continue; final decision = engine.decide(value); final candidate = decision.url; if (candidate == null || decision.method == PlayMethod.transcode) continue; final resolved = candidate.hasScheme ? candidate : Uri.parse(baseUrl).resolve(candidate.toString()); final token = _cleanToken(accessToken); if (token != null && !resolved.queryParameters.containsKey('api_key')) return resolved.replace(queryParameters: {...resolved.queryParameters, 'api_key': token}); return resolved; } throw RemuxConnectionException('Remux returned no playable media source'); }
  Future<void> reportPlaybackStarted({required String itemId, required String sessionId, String playMethod = 'DirectPlay', String? mediaSourceId}) async { this.sessionId = sessionId; final response = await _client.post(Uri.parse('$baseUrl/Sessions/Playing'), headers: _headers, body: jsonEncode({'ItemId': itemId, 'SessionId': sessionId, 'MediaSourceId': mediaSourceId ?? itemId, 'PlayMethod': playMethod, 'IsPaused': false})); _check(response); }
  Future<void> reportPlaybackProgress({required String itemId, required Duration position, required Duration duration, bool isPaused = false, String playMethod = 'DirectPlay', String? mediaSourceId}) async { final activeSession = sessionId; if (activeSession == null) return; final response = await _client.post(Uri.parse('$baseUrl/Sessions/Playing/Progress'), headers: _headers, body: jsonEncode({'ItemId': itemId, 'SessionId': activeSession, 'PositionTicks': position.inMicroseconds * 10, 'MediaSourceId': mediaSourceId ?? itemId, 'IsPaused': isPaused, 'PlayMethod': playMethod, 'EventName': 'timeupdate', 'RunTimeTicks': duration.inMicroseconds * 10})); _check(response); }
  Future<void> reportPlaybackStopped({required String itemId, required Duration position, String playMethod = 'DirectPlay', String? mediaSourceId}) async { final activeSession = sessionId; if (activeSession == null) return; final response = await _client.post(Uri.parse('$baseUrl/Sessions/Playing/Stopped'), headers: _headers, body: jsonEncode({'ItemId': itemId, 'SessionId': sessionId, 'MediaSourceId': mediaSourceId ?? itemId, 'PositionTicks': position.inMicroseconds * 10, 'PlayMethod': playMethod})); _check(response); sessionId = null; }
  Future<void> reportProgress({required String itemId, required Duration position, required Duration duration, bool isPaused = false}) => reportPlaybackProgress(itemId: itemId, position: position, duration: duration, isPaused: isPaused);
  void _check(http.Response response) { if (response.statusCode < 200 || response.statusCode >= 300) throw RemuxConnectionException('Remux request failed (${response.statusCode})', statusCode: response.statusCode); }
  void close() => _client.close();
}
